# This file generates the GitHub Actions matrix
---
include:

 # sweep
  - board: seeeduino_xiao_ble
    shield: sweep_dongle dongle_display
    snippet: common-config studio-rpc-usb-uart
    artifact-name: sweep_dongle
#  - board: nice_nano_v2
#    shield: sweep_left led_indicator
#    snippet: common-config studio-rpc-usb-uart
#    artifact-name: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_left led_indicator
    snippet: common-config
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_right led_indicator
    snippet: common-config
    artifact-name: sweep_peripheral_right

#  - board: seeeduino_xiao_ble
#    shield: sweep_dongle dongle_display
#    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
#    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
#    artifact-name: sweep_dongle_with_logging
#  - board: nice_nano_v2
#    shield: sweep_left led_indicator
#    snippet: common-config zmk-usb-logging studio-rpc-usb-uart
#    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
#    artifact-name: sweep_central_left_with_logging

  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    
  # reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
